import { ClerkProvider, UserButton } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" style={{ colorScheme: "dark light" }}>
        <body className={inter.className}>
          <header className="flex items-center justify-between">
            <Link href="/">
              <h1>Dannit</h1>
            </Link>
            <div className="flex items-center">
              <nav>
                <a href="/">Home</a>
                <a href="/about">About</a>
              </nav>
              <UserButton afterSignOutUrl="/" />
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
